name: matrix_link_text
description: Easy to use text widget for Flutter apps, which converts inlined urls into working, clickable links. Allows for custom styling. Supports matrix identifiers
version: 0.3.0
author: Aleksander Woźniak <aleksanderwozniak96@gmail.com>, Sorunome <mail@sorunome.de>
homepage: https://github.com/Sorunome/matrix_link_text

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^5.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.12.2
  punycode: ^0.1.0

flutter:
